### ISSUE TITLE
Does not check for Android 2.x

### ISSUE THREAD

**Issue by Arithmomaniac** [stormid/storm-svgmagic#8]
which is the other major browser to not support SVG

**Comment by Philo** [comment]
Thanks for reporting this, I'll look to add a check for android v2.x next week

**Comment by Philo** [comment]
http://www.nuget.org/packages/Storm.SvgMagic

v1.0.6 is published to nuget to resolve this issue.

Please review the updated readme info regarding the use of App_Browsers browser definitions
